# Form implementation generated from reading ui file 'Prac1gui.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_ingresar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_ingresar.setGeometry(QtCore.QRect(260, 60, 121, 30))
        self.bt_ingresar.setStyleSheet("QPushButton{\n"
"    \n"
"        background-color:rgb(198, 198, 198);\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"        color:rgb(0, 0, 0);\n"
"        border-radius: 15px;\n"
"border:1px soild #00007f;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"        background-color:rgb(255, 255, 255);\n"
"        font: 8pt \"MS Shell Dlg 2\";\n"
"        border-radius: 15px;\n"
"        color:rgb(0, 0, 0);\n"
"border:1px soild #00007f;\n"
"\n"
"}\n"
"")
        self.bt_ingresar.setObjectName("bt_ingresar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 291, 91))
        self.label_5.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 291, 91))
        self.label_6.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 370, 291, 91))
        self.label_7.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 460, 291, 91))
        self.label_8.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 550, 291, 91))
        self.label_9.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 12pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.CaracTo = QtWidgets.QLabel(self.centralwidget)
        self.CaracTo.setGeometry(QtCore.QRect(300, 190, 221, 91))
        self.CaracTo.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.CaracTo.setText("")
        self.CaracTo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CaracTo.setObjectName("CaracTo")
        self.Entropia = QtWidgets.QLabel(self.centralwidget)
        self.Entropia.setGeometry(QtCore.QRect(300, 280, 221, 91))
        self.Entropia.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.Entropia.setText("")
        self.Entropia.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Entropia.setObjectName("Entropia")
        self.CantidadDeI = QtWidgets.QLabel(self.centralwidget)
        self.CantidadDeI.setGeometry(QtCore.QRect(300, 370, 221, 91))
        self.CantidadDeI.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.CantidadDeI.setText("")
        self.CantidadDeI.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CantidadDeI.setObjectName("CantidadDeI")
        self.Eficiencia = QtWidgets.QLabel(self.centralwidget)
        self.Eficiencia.setGeometry(QtCore.QRect(300, 550, 221, 91))
        self.Eficiencia.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.Eficiencia.setText("")
        self.Eficiencia.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Eficiencia.setObjectName("Eficiencia")
        self.Redundancia = QtWidgets.QLabel(self.centralwidget)
        self.Redundancia.setGeometry(QtCore.QRect(300, 460, 221, 91))
        self.Redundancia.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.Redundancia.setText("")
        self.Redundancia.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Redundancia.setObjectName("Redundancia")
        self.cantletra = QtWidgets.QLabel(self.centralwidget)
        self.cantletra.setGeometry(QtCore.QRect(420, 75, 71, 21))
        self.cantletra.setStyleSheet("background-color: rgba(0, 0, 0 ,50%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.cantletra.setText("")
        self.cantletra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cantletra.setObjectName("cantletra")
        self.rutadelArc = QtWidgets.QLabel(self.centralwidget)
        self.rutadelArc.setGeometry(QtCore.QRect(10, 40, 251, 61))
        self.rutadelArc.setStyleSheet("background-color:rgb(198, 198, 198);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border:1px soild #00007f;\n"
"\n"
"")
        self.rutadelArc.setText("")
        self.rutadelArc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rutadelArc.setObjectName("rutadelArc")
        self.letra = QtWidgets.QLineEdit(self.centralwidget)
        self.letra.setGeometry(QtCore.QRect(420, 50, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.letra.setFont(font)
        self.letra.setStyleSheet("background:rgb(255, 219, 167);\n"
"border-radius: 10px;\n"
"Border:None;")
        self.letra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.letra.setObjectName("letra")
        self.letra_incorrecta = QtWidgets.QLabel(self.centralwidget)
        self.letra_incorrecta.setGeometry(QtCore.QRect(400, 100, 101, 51))
        self.letra_incorrecta.setStyleSheet("background-color: rgba(0, 0, 0 , 0%);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 0, 0);\n"
"border:none;")
        self.letra_incorrecta.setText("")
        self.letra_incorrecta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.letra_incorrecta.setObjectName("letra_incorrecta")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(420, 25, 71, 21))
        self.label_10.setStyleSheet("background-color: rgb(17, 212, 255);\n"
"font: 10pt \"Arial\";\n"
"color:rgb(255, 255, 255);\n"
"border:none;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_ingresar.setText(_translate("MainWindow", "Seleccionar archivo"))
        self.label_5.setText(_translate("MainWindow", "CANTIDAD DE CARACTERES LEIDOS"))
        self.label_6.setText(_translate("MainWindow", "ENTROPIA"))
        self.label_7.setText(_translate("MainWindow", "CANTIDAD DE INFORMAICON TORAL"))
        self.label_8.setText(_translate("MainWindow", "REDUNDANCIA"))
        self.label_9.setText(_translate("MainWindow", "EFICIENCIA"))
        self.letra.setText(_translate("MainWindow", "a"))
        self.letra.setPlaceholderText(_translate("MainWindow", "letra"))
        self.label_10.setText(_translate("MainWindow", "LETRA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
